remote_theme: artemsheludko/flexible-jekyll
title: Hello, world! I'm Jisung Park
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://IllIIIllll.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jisung Park # add your name
author-img: my.jpg # add your photo
about-author: I am passionate Machine Learning developer. Always hungry to keep learning. # add description
social-github: IllIIIllll # add your Github handle
social-email: llllllllll@kakao.com # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]